import React, { Component } from 'react';

export class About extends Component {
    render() {

    return (

        <div>
            <p style={{ marginTop: '0cm', marginRight: '0cm', marginBottom: '.0001pt', marginLeft: '0cm', lineHeight: '67.5pt', fontSize: '15px', fontFamily: '"Calibri","sans-serif"', textAlign: 'center', background: 'white' }}><span style={{ fontSize: '33px', fontFamily: '"DauphinPlain","serif"', color: 'black' }}>Lorem Ipsum</span></p>
            <p style={{ marginTop: '7.5pt', marginRight: '7.5pt', marginBottom: '3.75pt', marginLeft: '7.5pt', lineHeight: '13.5pt', fontSize: '15px', fontFamily: '"Calibri","sans-serif"', textAlign: 'center', background: 'white' }}><em><span style={{ fontSize: '14px', fontFamily: '"Arial","sans-serif"', color: 'black' }}>"Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..."</span></em></p>
            <p style={{ marginTop: '0cm', marginRight: '0cm', marginBottom: '11.25pt', marginLeft: '0cm', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Calibri","sans-serif"', textAlign: 'justify', background: 'white' }}><span style={{ fontSize: '14px', fontFamily: '"Arial","sans-serif"', color: 'black' }}>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean vel bibendum dolor, vel auctor nisl. Vestibulum nibh augue, tincidunt ac enim non, lacinia suscipit neque. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla convallis accumsan auctor. Cras vitae fringilla nulla. Curabitur vulputate diam ac odio ullamcorper, vel consequat erat egestas. In hac habitasse platea dictumst. Vestibulum imperdiet vestibulum diam eget rhoncus. Donec molestie nisl massa, ut egestas elit vestibulum id. Donec luctus turpis vitae porta molestie. Aliquam odio velit, mollis et elit nec, egestas feugiat enim. Integer vel sapien ipsum. In ac euismod diam. Nunc vulputate venenatis dictum. Cras ac eros ac leo faucibus tincidunt. Nunc at orci imperdiet, congue risus ut, semper mi.</span></p>
            <p style={{ marginTop: '0cm', marginRight: '0cm', marginBottom: '11.25pt', marginLeft: '0cm', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Calibri","sans-serif"', textAlign: 'justify', background: 'white' }}><span style={{ fontSize: '14px', fontFamily: '"Arial","sans-serif"', color: 'black' }}>Sed et purus urna. Fusce dapibus enim bibendum libero varius, ac euismod dui posuere. Vestibulum eget ex a ex cursus posuere. Proin iaculis maximus ipsum, non euismod erat dapibus a. Proin interdum dolor eget mauris faucibus, vel eleifend lorem fermentum. Sed bibendum mi porta ex porta dignissim. Donec aliquet est vel urna lobortis imperdiet. Cras non velit at nisl egestas sagittis id et enim. Nam non nulla dui. Nullam nunc erat, posuere quis risus quis, accumsan consectetur mi. Donec et dictum lacus. In arcu massa, tempus sed est quis, hendrerit sodales massa. Praesent aliquam libero nibh, sed suscipit augue pellentesque finibus. Phasellus varius auctor orci a tempus. Maecenas accumsan ultricies ex sed lacinia. Vestibulum eget tempus nisl.</span></p>
            <p style={{ marginTop: '0cm', marginRight: '0cm', marginBottom: '11.25pt', marginLeft: '0cm', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Calibri","sans-serif"', textAlign: 'justify', background: 'white' }}><span style={{ fontSize: '14px', fontFamily: '"Arial","sans-serif"', color: 'black' }}>Etiam efficitur condimentum turpis, a mattis justo consectetur sollicitudin. Pellentesque placerat, metus sed volutpat mollis, enim quam lacinia sem, et vehicula nibh sapien eu mauris. Quisque congue massa at nibh vestibulum dictum. Nullam turpis nisl, sodales quis quam sit amet, euismod tempor mauris. In gravida libero id mollis accumsan. Curabitur et dapibus odio. Proin nulla risus, vulputate semper ultricies quis, venenatis nec neque. Suspendisse tempus tortor id augue maximus, sed tempor mauris tempor. Proin tristique iaculis purus, a blandit massa. Maecenas eget placerat ex, id ullamcorper orci. Integer id diam sollicitudin, iaculis ligula posuere, fermentum libero. In gravida neque quis elementum scelerisque.</span></p>
            <p style={{ marginTop: '0cm', marginRight: '0cm', marginBottom: '11.25pt', marginLeft: '0cm', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Calibri","sans-serif"', textAlign: 'justify', background: 'white' }}><span style={{ fontSize: '14px', fontFamily: '"Arial","sans-serif"', color: 'black' }}>In hac habitasse platea dictumst. In consequat libero at turpis cursus, ut iaculis risus consectetur. Nunc imperdiet at libero quis tempor. Etiam metus augue, viverra nec viverra eu, luctus et augue. Proin in magna quis lacus molestie maximus. Curabitur fringilla justo ex, ac consequat nisl varius at. Pellentesque aliquet turpis et tortor lobortis elementum. Sed tincidunt quam a est fringilla, quis sollicitudin enim pellentesque. Cras tempus, velit at pulvinar eleifend, ante massa suscipit diam, eget ullamcorper justo nisi in sem. Morbi imperdiet suscipit quam. Suspendisse ut ullamcorper ante. Phasellus lobortis diam nunc, eu faucibus turpis ullamcorper vel. Donec id ipsum id odio gravida cursus nec nec risus. Aenean ultricies arcu et interdum laoreet. Sed nec ultrices erat, eget vestibulum orci.</span></p>
            <p style={{ marginTop: '0cm', marginRight: '0cm', marginBottom: '11.25pt', marginLeft: '0cm', lineHeight: 'normal', fontSize: '15px', fontFamily: '"Calibri","sans-serif"', textAlign: 'justify', background: 'white' }}><span style={{ fontSize: '14px', fontFamily: '"Arial","sans-serif"', color: 'black' }}>Vivamus pharetra vulputate nibh, vitae finibus nunc posuere nec. Pellentesque ac cursus felis. Nullam consequat porta odio sit amet rutrum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse at ligula efficitur, aliquet velit eu, tempus sem. Fusce a interdum ex, at tincidunt neque. Vivamus ac enim ante. Sed facilisis lacus id leo placerat, ut tincidunt nibh pulvinar.</span></p>
            <p style={{ marginTop: '0cm', marginRight: '0cm', marginBottom: '10.0pt', marginLeft: '0cm', lineHeight: '115%', fontSize: '15px', fontFamily: '"Calibri","sans-serif"' }}>&nbsp;</p>
        </div>

    );
    }


}